name: Run Postman tests with Newman

on:
  push:
    branches:
      - github-actions
    paths:
      - 'collection/**'
  workflow_dispatch: {}

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman tests
        run: |
          newman run collection/Restful_Booker_Collection.json \
            -e collection/Restful_Booker_Environment.json \
            --reporters cli,html \
            --reporter-html-export newman/html-report/report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: newman/html-report/report.html
